<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir)).'/ee-installer';

return array(
    '' => array($vendorDir . '/elastic-email/web-api-client/src'),
);
